// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7TEjdCQyQ_qsfrX0wPW2_JapgbCosIU',
    appId: '1:833765741392:web:7886e60a5c471485e11255',
    messagingSenderId: '833765741392',
    projectId: 'notepads-29b86',
    authDomain: 'notepads-29b86.firebaseapp.com',
    storageBucket: 'notepads-29b86.appspot.com',
    measurementId: 'G-B00HMPEFHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr95WWoiBGAnKlWJq8fTAGuCARPju2IdU',
    appId: '1:833765741392:android:6e17b493319e4f87e11255',
    messagingSenderId: '833765741392',
    projectId: 'notepads-29b86',
    storageBucket: 'notepads-29b86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAihU83_C-0Yw7Gw60i7GMiFt8n6e5aKM4',
    appId: '1:833765741392:ios:d0cde59c7f87b9b3e11255',
    messagingSenderId: '833765741392',
    projectId: 'notepads-29b86',
    storageBucket: 'notepads-29b86.appspot.com',
    iosClientId: '833765741392-pe4ne3dmg1024j47q7eitcbjsqo11orc.apps.googleusercontent.com',
    iosBundleId: 'com.pixolity.notepadex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAihU83_C-0Yw7Gw60i7GMiFt8n6e5aKM4',
    appId: '1:833765741392:ios:d0cde59c7f87b9b3e11255',
    messagingSenderId: '833765741392',
    projectId: 'notepads-29b86',
    storageBucket: 'notepads-29b86.appspot.com',
    iosClientId: '833765741392-pe4ne3dmg1024j47q7eitcbjsqo11orc.apps.googleusercontent.com',
    iosBundleId: 'com.pixolity.notepadex',
  );
}
